openapi: 3.0.1
info:
  title: exporter-S3-downloads
  description: map exporter S3 download proxy
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
paths:
  /download/{key}:
    get:
      operationId: download
      tags:
        - downloads
      summary: download the requested file
      parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: the value is `attachment; filename="<file name>"`
              schema:
                type: string
        404:
          description: NOT FOUND
